VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IRandomizer"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Battleship")
'@Interface
Option Explicit

Public Function NextSingle() As Single
End Function

Public Function Between(ByVal lower As Long, ByVal upper As Long) As Long
End Function
